services:
  - type: web
    name: sheetbridge
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app.main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: API_KEY
        sync: false
      - key: GOOGLE_CREDENTIALS_PATH
        value: credentials/service_account.json
